name: MCAnalytics
main: net.jmhertlein.mcanalytics.plugin.MCAnalyticsPlugin
version: ${version}
commands:
    mca:
        description: Base command for MCAnalytics
        usage: /mca (todo fix this)
        aliases:
